### PR TITLE
Feature/frontend updates

### PR DESCRIPTION
**Pull request by DiagonalJ117**
- Frontend Fixes
- File typo fixes
- Added Dark theme toggle functionality

### CODE REVIEW

**Comment by p0nch0d3v** [comment]
Could you please add images on how the application looks after updates ?

**Comment by DiagonalJ117** [comment]
> Could you please add images on how the application looks after updates ?

Sure! Here's some screenshots

image

image


image

image

**Review by p0nch0d3v — APPROVED** [review]
@DiagonalJ117 Approved to merge

**Comment by p0nch0d3v** [comment]
Issue related, #95

**Pull request merged**
